import Header from "@/components/Header";
import "../../styles/globals.css";

export const metadata = {
  title: "Investment App",
  description: "Generated by olatoy create app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Header />
        {children}
      </body>
    </html>
  );
}
